name: CrozzRoads
favicon: null
layout_spectrum: 0.9299832640681416
typography_spectrum: 0.6792690048459917
title: CrozzRoads Share
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3819274341221899
  lightness: 0.8716030102223158
  saturation: 0.8037631867919117
  rhythmicContrast: 0.28945642057806253
purpose: []
