name: CrozzRoads
favicon: null
layout_spectrum: 1
typography_spectrum: 0.38207
title: CrozzRoads Share
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#111111'
    - '#ffffff'
    - '#a5a5a5'
    - '#5c5c5c'
    - '#ec090c'
  brandStrength: 0.5
  lightness: 0.8716030102223158
  saturation: 0.8037631867919117
  rhythmicContrast: 0.28945642057806253
purpose: []
